
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.4 EDK_O.87xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_AXI_CFG_FPGA_0_DEVICE_ID,
		XPAR_AXI_CFG_FPGA_0_BASEADDR,
		XPAR_AXI_CFG_FPGA_0_INTERRUPT_PRESENT,
		XPAR_AXI_CFG_FPGA_0_IS_DUAL
	}
};


