#ChipScope Core Inserter Project File Version 3.0
#Fri May 10 16:19:13 PDT 2013
Project.device.designInputFile=/home/tinghui.wang/Workspace/NetFPGA7/git_repo/netfpga-cml/projects/loopback_test_nf7/hw/implementation/system_all.ngc
Project.device.designOutputFile=/home/tinghui.wang/Workspace/NetFPGA7/git_repo/netfpga-cml/projects/loopback_test_nf7/hw/implementation/system.ngc
Project.device.deviceFamily=20
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/tinghui.wang/Workspace/NetFPGA7/git_repo/netfpga-cml/projects/loopback_test_nf7/hw/implementation
Project.device.useSRL16=true
Project.filter.dimension=14
Project.filter<0>=*trimac_block*rx*
Project.filter<10>=*clk*
Project.filter<11>=*axis*
Project.filter<12>=axis*
Project.filter<13>=
Project.filter<1>=*trimac_block*tx*
Project.filter<2>=*trimac_block*
Project.filter<3>=*trimac_core*
Project.filter<4>=trimac_core*
Project.filter<5>=*rx*t*
Project.filter<6>=*rx*tdata*
Project.filter<7>=*rx*clk*
Project.filter<8>=*rx*
Project.filter<9>=*tx*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=2
Project.unit<0>.clockChannel=nf7_1g_interface_2 gtx_clk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=26
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/tx_axis_mac_tdata<7>
Project.unit<0>.triggerChannel<0><1>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/tx_axis_mac_tdata<6>
Project.unit<0>.triggerChannel<0><2>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/tx_axis_mac_tdata<5>
Project.unit<0>.triggerChannel<0><3>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/tx_axis_mac_tdata<4>
Project.unit<0>.triggerChannel<0><4>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/tx_axis_mac_tdata<3>
Project.unit<0>.triggerChannel<0><5>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/tx_axis_mac_tdata<2>
Project.unit<0>.triggerChannel<0><6>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/tx_axis_mac_tdata<1>
Project.unit<0>.triggerChannel<0><7>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/tx_axis_mac_tdata<0>
Project.unit<0>.triggerChannel<1><0>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/tx_axis_mac_tvalid
Project.unit<0>.triggerChannel<1><1>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/tx_axis_mac_tlast
Project.unit<0>.triggerChannel<1><2>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/tx_reset_int
Project.unit<0>.triggerChannel<1><3>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/tx_axis_mac_tready
Project.unit<0>.triggerChannel<1><4>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/tx_mac_reset
Project.unit<0>.triggerChannel<1><5>=
Project.unit<0>.triggerChannel<1><6>=
Project.unit<0>.triggerChannel<1><7>=
Project.unit<0>.triggerChannel<2><0>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_txd_int<7>
Project.unit<0>.triggerChannel<2><1>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_txd_int<6>
Project.unit<0>.triggerChannel<2><2>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_txd_int<5>
Project.unit<0>.triggerChannel<2><3>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_txd_int<4>
Project.unit<0>.triggerChannel<2><4>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_txd_int<3>
Project.unit<0>.triggerChannel<2><5>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_txd_int<2>
Project.unit<0>.triggerChannel<2><6>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_txd_int<1>
Project.unit<0>.triggerChannel<2><7>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_txd_int<0>
Project.unit<0>.triggerChannel<3><0>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_tx_en_int
Project.unit<0>.triggerChannel<3><1>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_tx_er_int
Project.unit<0>.triggerChannel<3><2>=
Project.unit<0>.triggerChannel<3><3>=
Project.unit<0>.triggerChannel<3><4>=
Project.unit<0>.triggerChannel<3><5>=
Project.unit<0>.triggerChannel<3><6>=
Project.unit<0>.triggerChannel<3><7>=
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerPortCount=4
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortWidth<0>=8
Project.unit<0>.triggerPortWidth<1>=5
Project.unit<0>.triggerPortWidth<2>=8
Project.unit<0>.triggerPortWidth<3>=2
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
Project.unit<1>.clockChannel=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/rx_mac_aclk_int
Project.unit<1>.clockEdge=Rising
Project.unit<1>.dataDepth=1024
Project.unit<1>.dataEqualsTrigger=true
Project.unit<1>.dataPortWidth=23
Project.unit<1>.enableGaps=false
Project.unit<1>.enableStorageQualification=true
Project.unit<1>.enableTimestamps=false
Project.unit<1>.timestampDepth=0
Project.unit<1>.timestampWidth=0
Project.unit<1>.triggerChannel<0><0>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/rx_axis_mac_tdata<7>
Project.unit<1>.triggerChannel<0><1>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/rx_axis_mac_tdata<6>
Project.unit<1>.triggerChannel<0><2>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/rx_axis_mac_tdata<5>
Project.unit<1>.triggerChannel<0><3>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/rx_axis_mac_tdata<4>
Project.unit<1>.triggerChannel<0><4>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/rx_axis_mac_tdata<3>
Project.unit<1>.triggerChannel<0><5>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/rx_axis_mac_tdata<2>
Project.unit<1>.triggerChannel<0><6>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/rx_axis_mac_tdata<1>
Project.unit<1>.triggerChannel<0><7>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/rx_axis_mac_tdata<0>
Project.unit<1>.triggerChannel<1><0>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/rx_reset_int
Project.unit<1>.triggerChannel<1><1>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/rx_axis_mac_tvalid
Project.unit<1>.triggerChannel<1><2>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/rx_axis_mac_tlast
Project.unit<1>.triggerChannel<1><3>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/rx_axis_mac_tuser
Project.unit<1>.triggerChannel<1><4>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/rx_mac_reset
Project.unit<1>.triggerChannel<1><5>=
Project.unit<1>.triggerChannel<1><6>=
Project.unit<1>.triggerChannel<1><7>=
Project.unit<1>.triggerChannel<2><0>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_rxd_int<7>
Project.unit<1>.triggerChannel<2><1>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_rxd_int<6>
Project.unit<1>.triggerChannel<2><2>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_rxd_int<5>
Project.unit<1>.triggerChannel<2><3>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_rxd_int<4>
Project.unit<1>.triggerChannel<2><4>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_rxd_int<3>
Project.unit<1>.triggerChannel<2><5>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_rxd_int<2>
Project.unit<1>.triggerChannel<2><6>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_rxd_int<1>
Project.unit<1>.triggerChannel<2><7>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_rxd_int<0>
Project.unit<1>.triggerChannel<3><0>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_rx_dv_int
Project.unit<1>.triggerChannel<3><1>=nf7_1g_interface_2 nf7_1g_interface_2/mac_fifo_block/trimac_block/gmii_rx_er_int
Project.unit<1>.triggerConditionCountWidth=0
Project.unit<1>.triggerMatchCount<0>=1
Project.unit<1>.triggerMatchCount<1>=1
Project.unit<1>.triggerMatchCount<2>=1
Project.unit<1>.triggerMatchCount<3>=1
Project.unit<1>.triggerMatchCountWidth<0><0>=0
Project.unit<1>.triggerMatchCountWidth<1><0>=0
Project.unit<1>.triggerMatchCountWidth<2><0>=0
Project.unit<1>.triggerMatchCountWidth<3><0>=0
Project.unit<1>.triggerMatchType<0><0>=1
Project.unit<1>.triggerMatchType<1><0>=1
Project.unit<1>.triggerMatchType<2><0>=1
Project.unit<1>.triggerMatchType<3><0>=1
Project.unit<1>.triggerPortCount=4
Project.unit<1>.triggerPortIsData<0>=true
Project.unit<1>.triggerPortIsData<1>=true
Project.unit<1>.triggerPortIsData<2>=true
Project.unit<1>.triggerPortIsData<3>=true
Project.unit<1>.triggerPortWidth<0>=8
Project.unit<1>.triggerPortWidth<1>=5
Project.unit<1>.triggerPortWidth<2>=8
Project.unit<1>.triggerPortWidth<3>=2
Project.unit<1>.triggerSequencerLevels=16
Project.unit<1>.triggerSequencerType=1
Project.unit<1>.type=ilapro
