#ChipScope Core Inserter Project File Version 3.0
#Mon May 13 17:51:11 PDT 2013
Project.device.designInputFile=/home/tinghui.wang/Workspace/NetFPGA7/git_repo/netfpga-cml/projects/loopback_test_nf7/hw/implementation/system_all.ngc
Project.device.designOutputFile=/home/tinghui.wang/Workspace/NetFPGA7/git_repo/netfpga-cml/projects/loopback_test_nf7/hw/implementation/system.ngc
Project.device.deviceFamily=20
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/tinghui.wang/Workspace/NetFPGA7/git_repo/netfpga-cml/projects/loopback_test_nf7/hw/implementation
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=*gmii_rx*
Project.filter<10>=*tuser*
Project.filter<11>=*tx_axis_mac*
Project.filter<12>=*tdata*
Project.filter<13>=
Project.filter<14>=*trimac_block*rx*
Project.filter<15>=*trimac_block*tx*
Project.filter<16>=*trimac_block*
Project.filter<17>=*trimac_core*
Project.filter<18>=trimac_core*
Project.filter<1>=*rx_axis_mac*
Project.filter<2>=*rx_axi_mac*
Project.filter<3>=*rx_axi*
Project.filter<4>=*rx_mac*
Project.filter<5>=*gmii_tx*
Project.filter<6>=*txd*
Project.filter<7>=*gmii_txd*
Project.filter<8>=*reset*
Project.filter<9>=*tx_reset*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=2
Project.unit<0>.clockChannel=nf7_1g_interface_4 gtx_clk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<7>
Project.unit<0>.dataChannel<10>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tlast
Project.unit<0>.dataChannel<11>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<7>
Project.unit<0>.dataChannel<12>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<6>
Project.unit<0>.dataChannel<13>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<5>
Project.unit<0>.dataChannel<14>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<4>
Project.unit<0>.dataChannel<15>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<3>
Project.unit<0>.dataChannel<16>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<2>
Project.unit<0>.dataChannel<17>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<1>
Project.unit<0>.dataChannel<18>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<0>
Project.unit<0>.dataChannel<19>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txer_out_reg
Project.unit<0>.dataChannel<1>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<6>
Project.unit<0>.dataChannel<20>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txen_out_reg
Project.unit<0>.dataChannel<2>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<5>
Project.unit<0>.dataChannel<3>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<4>
Project.unit<0>.dataChannel<4>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<3>
Project.unit<0>.dataChannel<5>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<2>
Project.unit<0>.dataChannel<6>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<1>
Project.unit<0>.dataChannel<7>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<0>
Project.unit<0>.dataChannel<8>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tready
Project.unit<0>.dataChannel<9>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tvalid
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=21
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<7>
Project.unit<0>.triggerChannel<0><1>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<6>
Project.unit<0>.triggerChannel<0><2>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<5>
Project.unit<0>.triggerChannel<0><3>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<4>
Project.unit<0>.triggerChannel<0><4>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<3>
Project.unit<0>.triggerChannel<0><5>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<2>
Project.unit<0>.triggerChannel<0><6>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<1>
Project.unit<0>.triggerChannel<0><7>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tdata<0>
Project.unit<0>.triggerChannel<1><0>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tready
Project.unit<0>.triggerChannel<1><1>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tvalid
Project.unit<0>.triggerChannel<1><2>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/tx_axis_mac_tlast
Project.unit<0>.triggerChannel<2><0>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<7>
Project.unit<0>.triggerChannel<2><1>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<6>
Project.unit<0>.triggerChannel<2><2>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<5>
Project.unit<0>.triggerChannel<2><3>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<4>
Project.unit<0>.triggerChannel<2><4>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<3>
Project.unit<0>.triggerChannel<2><5>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<2>
Project.unit<0>.triggerChannel<2><6>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<1>
Project.unit<0>.triggerChannel<2><7>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txd_out_reg<0>
Project.unit<0>.triggerChannel<3><0>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txer_out_reg
Project.unit<0>.triggerChannel<3><1>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/ucsd_gig_eth_mac/mac_tx/gmii_txen_out_reg
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerPortCount=4
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortWidth<0>=8
Project.unit<0>.triggerPortWidth<1>=3
Project.unit<0>.triggerPortWidth<2>=8
Project.unit<0>.triggerPortWidth<3>=2
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
Project.unit<1>.clockChannel=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/rx_mac_aclk_int
Project.unit<1>.clockEdge=Rising
Project.unit<1>.dataChannel<0>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<7>
Project.unit<1>.dataChannel<10>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tlast
Project.unit<1>.dataChannel<11>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<7>
Project.unit<1>.dataChannel<12>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<6>
Project.unit<1>.dataChannel<13>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<5>
Project.unit<1>.dataChannel<14>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<4>
Project.unit<1>.dataChannel<15>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<3>
Project.unit<1>.dataChannel<16>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<2>
Project.unit<1>.dataChannel<17>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<1>
Project.unit<1>.dataChannel<18>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<0>
Project.unit<1>.dataChannel<19>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rx_er_int
Project.unit<1>.dataChannel<1>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<6>
Project.unit<1>.dataChannel<20>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rx_dv_int
Project.unit<1>.dataChannel<2>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<5>
Project.unit<1>.dataChannel<3>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<4>
Project.unit<1>.dataChannel<4>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<3>
Project.unit<1>.dataChannel<5>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<2>
Project.unit<1>.dataChannel<6>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<1>
Project.unit<1>.dataChannel<7>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<0>
Project.unit<1>.dataChannel<8>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tvalid
Project.unit<1>.dataChannel<9>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tuser
Project.unit<1>.dataDepth=1024
Project.unit<1>.dataEqualsTrigger=true
Project.unit<1>.dataPortWidth=21
Project.unit<1>.enableGaps=false
Project.unit<1>.enableStorageQualification=true
Project.unit<1>.enableTimestamps=false
Project.unit<1>.timestampDepth=0
Project.unit<1>.timestampWidth=0
Project.unit<1>.triggerChannel<0><0>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<7>
Project.unit<1>.triggerChannel<0><1>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<6>
Project.unit<1>.triggerChannel<0><2>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<5>
Project.unit<1>.triggerChannel<0><3>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<4>
Project.unit<1>.triggerChannel<0><4>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<3>
Project.unit<1>.triggerChannel<0><5>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<2>
Project.unit<1>.triggerChannel<0><6>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<1>
Project.unit<1>.triggerChannel<0><7>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tdata<0>
Project.unit<1>.triggerChannel<1><0>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tvalid
Project.unit<1>.triggerChannel<1><1>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tuser
Project.unit<1>.triggerChannel<1><2>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/rx_axis_mac_tlast
Project.unit<1>.triggerChannel<2><0>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<7>
Project.unit<1>.triggerChannel<2><1>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<6>
Project.unit<1>.triggerChannel<2><2>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<5>
Project.unit<1>.triggerChannel<2><3>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<4>
Project.unit<1>.triggerChannel<2><4>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<3>
Project.unit<1>.triggerChannel<2><5>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<2>
Project.unit<1>.triggerChannel<2><6>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<1>
Project.unit<1>.triggerChannel<2><7>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rxd_int<0>
Project.unit<1>.triggerChannel<3><0>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rx_er_int
Project.unit<1>.triggerChannel<3><1>=nf7_1g_interface_4 nf7_1g_interface_4/gig_eth_mac_fifo_block/gig_eth_mac_block/gmii_rx_dv_int
Project.unit<1>.triggerConditionCountWidth=0
Project.unit<1>.triggerMatchCount<0>=1
Project.unit<1>.triggerMatchCount<1>=1
Project.unit<1>.triggerMatchCount<2>=1
Project.unit<1>.triggerMatchCount<3>=1
Project.unit<1>.triggerMatchCountWidth<0><0>=0
Project.unit<1>.triggerMatchCountWidth<1><0>=0
Project.unit<1>.triggerMatchCountWidth<2><0>=0
Project.unit<1>.triggerMatchCountWidth<3><0>=0
Project.unit<1>.triggerMatchType<0><0>=1
Project.unit<1>.triggerMatchType<1><0>=1
Project.unit<1>.triggerMatchType<2><0>=1
Project.unit<1>.triggerMatchType<3><0>=1
Project.unit<1>.triggerPortCount=4
Project.unit<1>.triggerPortIsData<0>=true
Project.unit<1>.triggerPortIsData<1>=true
Project.unit<1>.triggerPortIsData<2>=true
Project.unit<1>.triggerPortIsData<3>=true
Project.unit<1>.triggerPortWidth<0>=8
Project.unit<1>.triggerPortWidth<1>=3
Project.unit<1>.triggerPortWidth<2>=8
Project.unit<1>.triggerPortWidth<3>=2
Project.unit<1>.triggerSequencerLevels=16
Project.unit<1>.triggerSequencerType=1
Project.unit<1>.type=ilapro
