################################################################################
#
#  NetFPGA-10G http://www.netfpga.org
#
#  File:
#        xparam2regdefines.py
#
#  Project:
#        Python Test Infrastructure 
#
#  Module:
#       Python Library Files 
#
#  Author:
#        Neelakandan Manihatty Bojan
#
#  Description:
#        Makefiles for the Python test infrastructure
#
#  Copyright notice:
#        Copyright (C) 2013 University of Cambridge
#
#  Licence:
#        This file is part of the NetFPGA 10G development base package.
#
#        This file is free code: you can redistribute it and/or modify it under
#        the terms of the GNU Lesser General Public License version 2.1 as
#        published by the Free Software Foundation.
#
#        This package is distributed in the hope that it will be useful, but
#        WITHOUT ANY WARRANTY; without even the implied warranty of
#        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#        Lesser General Public License for more details.
#
#        You should have received a copy of the GNU Lesser General Public
#        License along with the NetFPGA source package.  If not, see
#        http://www.gnu.org/licenses/.
#
#

clean:
	rm -f *.pyc
	rm -f ../*.pyc

.PHONY: clean

