################################################################################
#
#  NetFPGA-10G http://www.netfpga.org
#
#  File:
#        Makefile
#
#  Project:
#        reference_nic pcie programming cpld 
#
#  Author:
#        Jong Han
#
#  Description:
#			An image file of cpld.jed file is generated for pcie programming.
#
#  Copyright notice:
#        Copyright (C) 2013 University of Cambridge
#
#  Licence:
#        This file is part of the NetFPGA 10G development base package.
#
#        This file is free code: you can redistribute it and/or modify it under
#        the terms of the GNU Lesser General Public License version 2.1 as
#        published by the Free Software Foundation.
#
#        This package is distributed in the hope that it will be useful, but
#        WITHOUT ANY WARRANTY; without even the implied warranty of
#        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#        Lesser General Public License for more details.
#
#        You should have received a copy of the GNU Lesser General Public
#        License along with the NetFPGA source package.  If not, see
#        http://www.gnu.org/licenses/.
#
#

all:
	./cpld_run.sh
	
clean:
	@rm -rf  _ngo/
	@rm -rf  _xmsgs/
	@rm -rf  cpld.bld
	@rm -rf  cpld.chk
	@rm -rf  cpld.log
	@rm -rf  cpld.cmd_log
	@rm -rf  cpld.cxt
	@rm -rf  cpld.gise
	@rm -rf  cpld.gyd
	@rm -rf  cpld.jed
	@rm -rf  cpld.lso
	@rm -rf  cpld.mfd
	@rm -rf  cpld.nga
	@rm -rf  cpld.ngc
	@rm -rf  cpld.ngd
	@rm -rf  cpld.ngr
	@rm -rf  cpld.pad
	@rm -rf  cpld.pnx
	@rm -rf  cpld.rpt
	@rm -rf  cpld.stx
	@rm -rf  cpld.syr
	@rm -rf  cpld.tim
	@rm -rf  cpld.tspec
	@rm -rf  cpld.vm6
	@rm -rf  cpld.xml
	@rm -rf  cpld_build.xml
	@rm -rf  cpld_envsettings.html
	@rm -rf  cpld_html/
	@rm -rf  cpld_ngdbuild.xrpt
	@rm -rf  cpld_pad.csv
	@rm -rf  cpld_summary.html
	@rm -rf  cpld_xst.xrpt
	@rm -rf  iseconfig/
	@rm -rf  t1.dat
	@rm -rf  t1.phd
	@rm -rf  t55.dat
	@rm -rf  t55.phd
	@rm -rf  t6.dat
	@rm -rf  t6.phd
	@rm -rf  tmperr.err
	@rm -rf  webtalk_pn.xml
	@rm -rf  xlnx_auto_0_xdb/
	@rm -rf  xst/
	@echo
	@echo "CPLD files removed."
	
