#!/usr/bin/env python
from subprocess import Popen, PIPE

proc = Popen(["ifconfig","eth2","192.168.100.1"], stdout=PIPE)
proc = Popen(["ifconfig","eth3","192.168.101.1"], stdout=PIPE)
proc = Popen(["ifconfig","nf0","192.168.200.1"], stdout=PIPE)
proc = Popen(["ifconfig","nf1","192.168.201.1"], stdout=PIPE)
proc = Popen(["ifconfig","nf2","192.168.202.1"], stdout=PIPE)
proc = Popen(["ifconfig","nf3","192.168.203.1"], stdout=PIPE)

