#!/usr/bin/python
#############################################################
#
# Python register defines
#
# Project: Reference NIC (reference_nic)
# Description: Reference NIC
#
#############################################################

def STDIN_BASEADDRESS ():
    return 0x40600000
def STDOUT_BASEADDRESS ():
    return 0x40600000

#******************************************************************/

# Definitions for driver UARTLITE
def XPAR_XUARTLITE_NUM_INSTANCES():
    return 1

# Definitions for peripheral RS232_UART_1 

def XPAR_RS232_UART_1_BASEADDR (): 
    return 0x40600000
def XPAR_RS232_UART_1_HIGHADDR ():
    return 0x4060FFFF
def XPAR_RS232_UART_1_DEVICE_ID ():
    return 0
def XPAR_RS232_UART_1_BAUDRATE ():
    return 9600
def XPAR_RS232_UART_1_USE_PARITY ():
    return 0
def XPAR_RS232_UART_1_ODD_PARITY ():
    return 1
def XPAR_RS232_UART_1_DATA_BITS ():
    return 8


#******************************************************************

# Canonical definitions for peripheral RS232_UART_1 
def XPAR_UARTLITE_0_DEVICE_ID ():
    return XPAR_RS232_UART_1_DEVICE_ID
def XPAR_UARTLITE_0_BASEADDR ():
    return 0x40600000
def XPAR_UARTLITE_0_HIGHADDR ():
    return 0x4060FFFF
def XPAR_UARTLITE_0_BAUDRATE ():
    return 9600
def XPAR_UARTLITE_0_USE_PARITY ():
    return 0
def XPAR_UARTLITE_0_ODD_PARITY ():
    return 1
def XPAR_UARTLITE_0_DATA_BITS ():
    return 8
def XPAR_UARTLITE_0_SIO_CHAN ():
    return 0


#******************************************************************

# Definitions for driver WDTTB 

def XPAR_XWDTTB_NUM_INSTANCES ():
    return 1

# Definitions for peripheral AXI_TIMEBASE_WDT_0 
def XPAR_AXI_TIMEBASE_WDT_0_DEVICE_ID ():
    return 0
def XPAR_AXI_TIMEBASE_WDT_0_BASEADDR ():
    return 0x41A20000
def XPAR_AXI_TIMEBASE_WDT_0_HIGHADDR ():
    return 0x41A2FFFF


#******************************************************************

# Canonical definitions for peripheral AXI_TIMEBASE_WDT_0 
def XPAR_WDTTB_0_DEVICE_ID ():
    return XPAR_AXI_TIMEBASE_WDT_0_DEVICE_ID
def XPAR_WDTTB_0_BASEADDR ():
    return 0x41A20000
def XPAR_WDTTB_0_HIGHADDR ():
    return 0x41A2FFFF


#******************************************************************


# Definitions for peripheral DMA_0 
def XPAR_DMA_0_BASEADDR ():
    return 0x7D400000
def XPAR_DMA_0_HIGHADDR ():
    return 0x7D40FFFF


# Definitions for peripheral NF10_10G_INTERFACE_0 
def XPAR_NF10_10G_INTERFACE_0_BASEADDR ():
    return 0x5A000000
def XPAR_NF10_10G_INTERFACE_0_HIGHADDR ():
    return 0x5A00FFFF


# Definitions for peripheral NF10_10G_INTERFACE_1 
def XPAR_NF10_10G_INTERFACE_1_BASEADDR ():
    return 0x5B000000
def XPAR_NF10_10G_INTERFACE_1_HIGHADDR ():
    return 0x5B00FFFF


# Definitions for peripheral NF10_10G_INTERFACE_2 
def XPAR_NF10_10G_INTERFACE_2_BASEADDR ():
    return 0x5C000000
def XPAR_NF10_10G_INTERFACE_2_HIGHADDR ():
    return 0x5C00FFFF


#Definitions for peripheral NF10_10G_INTERFACE_3
def XPAR_NF10_10G_INTERFACE_3_BASEADDR ():
    return 0x5D000000
def XPAR_NF10_10G_INTERFACE_3_HIGHADDR ():
    return 0x5D00FFFF


#******************************************************************

# Definitions for driver BRAM 
def XPAR_XBRAM_NUM_INSTANCES ():
    return 2

# Definitions for peripheral MICROBLAZE_0_D_BRAM_CTRL 
def XPAR_MICROBLAZE_0_D_BRAM_CTRL_DEVICE_ID ():
    return 0
def XPAR_MICROBLAZE_0_D_BRAM_CTRL_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_D_BRAM_CTRL_ECC ():
    return 0
def XPAR_MICROBLAZE_0_D_BRAM_CTRL_FAULT_INJECT ():
    return 0
def XPAR_MICROBLAZE_0_D_BRAM_CTRL_CE_FAILING_REGISTERS ():
    return 0
def XPAR_MICROBLAZE_0_D_BRAM_CTRL_UE_FAILING_REGISTERS ():
    return 0
def XPAR_MICROBLAZE_0_D_BRAM_CTRL_ECC_STATUS_REGISTERS ():
    return 0
def XPAR_MICROBLAZE_0_D_BRAM_CTRL_CE_COUNTER_WIDTH ():
    return 0
def XPAR_MICROBLAZE_0_D_BRAM_CTRL_ECC_ONOFF_REGISTER ():
    return 0
def XPAR_MICROBLAZE_0_D_BRAM_CTRL_ECC_ONOFF_RESET_VALUE ():
    return 0
def XPAR_MICROBLAZE_0_D_BRAM_CTRL_WRITE_ACCESS ():
    return 0
def XPAR_MICROBLAZE_0_D_BRAM_CTRL_BASEADDR ():
    return 0x00000000
def XPAR_MICROBLAZE_0_D_BRAM_CTRL_HIGHADDR ():
    return 0x00003FFF


# Definitions for peripheral MICROBLAZE_0_I_BRAM_CTRL 
def XPAR_MICROBLAZE_0_I_BRAM_CTRL_DEVICE_ID ():
    return 1
def XPAR_MICROBLAZE_0_I_BRAM_CTRL_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_I_BRAM_CTRL_ECC ():
    return 0
def XPAR_MICROBLAZE_0_I_BRAM_CTRL_FAULT_INJECT ():
    return 0
def XPAR_MICROBLAZE_0_I_BRAM_CTRL_CE_FAILING_REGISTERS ():
    return 0
def XPAR_MICROBLAZE_0_I_BRAM_CTRL_UE_FAILING_REGISTERS ():
    return 0
def XPAR_MICROBLAZE_0_I_BRAM_CTRL_ECC_STATUS_REGISTERS ():
    return 0
def XPAR_MICROBLAZE_0_I_BRAM_CTRL_CE_COUNTER_WIDTH ():
    return 0
def XPAR_MICROBLAZE_0_I_BRAM_CTRL_ECC_ONOFF_REGISTER ():
    return 0
def XPAR_MICROBLAZE_0_I_BRAM_CTRL_ECC_ONOFF_RESET_VALUE ():
    return 0
def XPAR_MICROBLAZE_0_I_BRAM_CTRL_WRITE_ACCESS ():
    return 0
def XPAR_MICROBLAZE_0_I_BRAM_CTRL_BASEADDR ():
    return 0x00000000
def XPAR_MICROBLAZE_0_I_BRAM_CTRL_HIGHADDR ():
    return 0x00003FFF


#******************************************************************


# Canonical definitions for peripheral MICROBLAZE_0_D_BRAM_CTRL 
def XPAR_BRAM_0_DEVICE_ID ():
    return XPAR_MICROBLAZE_0_D_BRAM_CTRL_DEVICE_ID
def XPAR_BRAM_0_DATA_WIDTH ():
    return 32
def XPAR_BRAM_0_ECC ():
    return 0
def XPAR_BRAM_0_FAULT_INJECT ():
    return 0
def XPAR_BRAM_0_CE_FAILING_REGISTERS ():
    return 0
def XPAR_BRAM_0_UE_FAILING_REGISTERS ():
    return 0
def XPAR_BRAM_0_ECC_STATUS_REGISTERS ():
    return 0
def XPAR_BRAM_0_CE_COUNTER_WIDTH ():
    return 0
def XPAR_BRAM_0_ECC_ONOFF_REGISTER ():
    return 0
def XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE ():
    return 0
def XPAR_BRAM_0_WRITE_ACCESS ():
    return 0
def XPAR_BRAM_0_BASEADDR ():
    return 0x00000000
def XPAR_BRAM_0_HIGHADDR ():
    return 0x00003FFF

# Canonical definitions for peripheral MICROBLAZE_0_I_BRAM_CTRL 
def XPAR_BRAM_1_DEVICE_ID ():
    return XPAR_MICROBLAZE_0_I_BRAM_CTRL_DEVICE_ID
def XPAR_BRAM_1_DATA_WIDTH ():
    return 32
def XPAR_BRAM_1_ECC ():
    return 0
def XPAR_BRAM_1_FAULT_INJECT ():
    return 0
def XPAR_BRAM_1_CE_FAILING_REGISTERS ():
    return 0
def XPAR_BRAM_1_UE_FAILING_REGISTERS ():
    return 0
def XPAR_BRAM_1_ECC_STATUS_REGISTERS ():
    return 0
def XPAR_BRAM_1_CE_COUNTER_WIDTH ():
    return 0
def XPAR_BRAM_1_ECC_ONOFF_REGISTER ():
    return 0
def XPAR_BRAM_1_ECC_ONOFF_RESET_VALUE ():
    return 0
def XPAR_BRAM_1_WRITE_ACCESS ():
    return 0
def XPAR_BRAM_1_BASEADDR ():
    return 0x00000000
def XPAR_BRAM_1_HIGHADDR ():
    return 0x00003FFF


#******************************************************************

# Definitions for driver NF10_MDIO 
def XPAR_XEMACLITE_NUM_INSTANCES ():
    return 1

# Definitions for peripheral NF10_MDIO_0
def XPAR_NF10_MDIO_0_DEVICE_ID ():
    return 0
def XPAR_NF10_MDIO_0_BASEADDR ():
    return 0x7A000000
def XPAR_NF10_MDIO_0_HIGHADDR ():
    return 0x7A00FFFF
def XPAR_NF10_MDIO_0_TX_PING_PONG ():
    return 0
def XPAR_NF10_MDIO_0_RX_PING_PONG ():
    return 0
def XPAR_NF10_MDIO_0_INCLUDE_MDIO ():
    return 1
def XPAR_NF10_MDIO_0_INCLUDE_INTERNAL_LOOPBACK ():
    return 0


#******************************************************************

# Canonical definitions for peripheral NF10_MDIO_0 
def XPAR_EMACLITE_0_DEVICE_ID ():
    return XPAR_NF10_MDIO_0_DEVICE_ID
def XPAR_EMACLITE_0_BASEADDR ():
    return 0x7A000000
def XPAR_EMACLITE_0_HIGHADDR ():
    return 0x7A00FFFF
def XPAR_EMACLITE_0_TX_PING_PONG ():
    return 0
def XPAR_EMACLITE_0_RX_PING_PONG ():
    return 0
def XPAR_EMACLITE_0_INCLUDE_MDIO ():
    return 1
def XPAR_EMACLITE_0_INCLUDE_INTERNAL_LOOPBACK ():
    return 0


#******************************************************************

# Definitions for bus frequencies 
def XPAR_CPU_M_AXI_DP_FREQ_HZ (): 
    return 100000000
#******************************************************************

# Canonical definitions for bus frequencies 
def XPAR_PROC_BUS_0_FREQ_HZ ():
    return 100000000
#******************************************************************

def XPAR_CPU_CORE_CLOCK_FREQ_HZ ():
    return 100000000
def XPAR_MICROBLAZE_CORE_CLOCK_FREQ_HZ ():
    return 100000000

#******************************************************************


# Definitions for peripheral MICROBLAZE_0
def XPAR_MICROBLAZE_0_SCO ():
    return 0
def XPAR_MICROBLAZE_0_FREQ ():
    return 100000000
def XPAR_MICROBLAZE_0_DATA_SIZE ():
    return 32
def XPAR_MICROBLAZE_0_DYNAMIC_BUS_SIZING ():
    return 1
def XPAR_MICROBLAZE_0_FAULT_TOLERANT ():
    return 0
def XPAR_MICROBLAZE_0_ECC_USE_CE_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_0_ENDIANNESS ():
    return 1
def XPAR_MICROBLAZE_0_AREA_OPTIMIZED ():
    return 0
def XPAR_MICROBLAZE_0_OPTIMIZATION ():
    return 0
def XPAR_MICROBLAZE_0_INTERCONNECT ():
    return 2
def XPAR_MICROBLAZE_0_STREAM_INTERCONNECT ():
    return 0
def XPAR_MICROBLAZE_0_DPLB_DWIDTH ():
    return 32
def XPAR_MICROBLAZE_0_DPLB_NATIVE_DWIDTH ():
    return 32
def XPAR_MICROBLAZE_0_DPLB_BURST_EN ():
    return 0
def XPAR_MICROBLAZE_0_DPLB_P2P ():
    return 0
def XPAR_MICROBLAZE_0_IPLB_DWIDTH ():
    return 32
def XPAR_MICROBLAZE_0_IPLB_NATIVE_DWIDTH ():
    return 32
def XPAR_MICROBLAZE_0_IPLB_BURST_EN ():
    return 0
def XPAR_MICROBLAZE_0_IPLB_P2P ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_DP_SUPPORTS_THREADS ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_DP_THREAD_ID_WIDTH ():
    return 1
def XPAR_MICROBLAZE_0_M_AXI_DP_SUPPORTS_READ ():
    return 1
def XPAR_MICROBLAZE_0_M_AXI_DP_SUPPORTS_WRITE ():
    return 1
def XPAR_MICROBLAZE_0_M_AXI_DP_SUPPORTS_NARROW_BURST ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_DP_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M_AXI_DP_ADDR_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M_AXI_DP_PROTOCOL ():
    return AXI4LITE
def XPAR_MICROBLAZE_0_M_AXI_DP_EXCLUSIVE_ACCESS ():
    return 0
def XPAR_MICROBLAZE_0_INTERCONNECT_M_AXI_DP_READ_ISSUING ():
    return 1
def XPAR_MICROBLAZE_0_INTERCONNECT_M_AXI_DP_WRITE_ISSUING ():
    return 1
def XPAR_MICROBLAZE_0_M_AXI_IP_SUPPORTS_THREADS ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_IP_THREAD_ID_WIDTH ():
    return 1
def XPAR_MICROBLAZE_0_M_AXI_IP_SUPPORTS_READ ():
    return 1
def XPAR_MICROBLAZE_0_M_AXI_IP_SUPPORTS_WRITE ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_IP_SUPPORTS_NARROW_BURST ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_IP_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M_AXI_IP_ADDR_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M_AXI_IP_PROTOCOL ():
    return AXI4LITE
def XPAR_MICROBLAZE_0_INTERCONNECT_M_AXI_IP_READ_ISSUING ():
    return 1
def XPAR_MICROBLAZE_0_D_AXI ():
    return 1
def XPAR_MICROBLAZE_0_D_PLB ():
    return 0
def XPAR_MICROBLAZE_0_D_LMB ():
    return 1
def XPAR_MICROBLAZE_0_I_AXI ():
    return 0
def XPAR_MICROBLAZE_0_I_PLB ():
    return 0
def XPAR_MICROBLAZE_0_I_LMB ():
    return 1
def XPAR_MICROBLAZE_0_USE_MSR_INSTR ():
    return 1
def XPAR_MICROBLAZE_0_USE_PCMP_INSTR ():
    return 1
def XPAR_MICROBLAZE_0_USE_BARREL ():
    return 1
def XPAR_MICROBLAZE_0_USE_DIV ():
    return 0
def XPAR_MICROBLAZE_0_USE_HW_MUL ():
    return 0
def XPAR_MICROBLAZE_0_USE_FPU ():
    return 0
def XPAR_MICROBLAZE_0_UNALIGNED_EXCEPTIONS ():
    return 0
def XPAR_MICROBLAZE_0_ILL_OPCODE_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_I_BUS_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_D_BUS_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_0_IPLB_BUS_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_0_DPLB_BUS_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_0_DIV_ZERO_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_0_FPU_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_0_FSL_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_0_PVR ():
    return 0
def XPAR_MICROBLAZE_0_PVR_USER1 ():
    return 0x00
def XPAR_MICROBLAZE_0_PVR_USER2 ():
    return 0x00000000
def XPAR_MICROBLAZE_0_DEBUG_ENABLED ():
    return 0
def XPAR_MICROBLAZE_0_NUMBER_OF_PC_BRK ():
    return 1
def XPAR_MICROBLAZE_0_NUMBER_OF_RD_ADDR_BRK ():
    return 0
def XPAR_MICROBLAZE_0_NUMBER_OF_WR_ADDR_BRK ():
    return 0
def XPAR_MICROBLAZE_0_INTERRUPT_IS_EDGE ():
    return 0
def XPAR_MICROBLAZE_0_EDGE_IS_POSITIVE ():
    return 1
def XPAR_MICROBLAZE_0_RESET_MSR ():
    return 0x00000000
def XPAR_MICROBLAZE_0_OPCODE_0X0_ILLEGAL ():
    return 0
def XPAR_MICROBLAZE_0_FSL_LINKS ():
    return 0
def XPAR_MICROBLAZE_0_FSL_DATA_SIZE ():
    return 32
def XPAR_MICROBLAZE_0_USE_EXTENDED_FSL_INSTR ():
    return 0
def XPAR_MICROBLAZE_0_M0_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S0_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M1_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S1_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M2_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S2_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M3_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S3_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M4_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S4_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M5_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S5_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M6_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S6_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M7_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S7_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M8_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S8_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M9_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S9_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M10_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S10_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M11_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S11_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M12_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S12_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M13_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S13_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M14_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S14_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M15_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_S15_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_0_M0_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S0_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M1_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S1_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M2_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S2_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M3_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S3_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M4_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S4_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M5_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S5_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M6_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S6_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M7_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S7_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M8_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S8_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M9_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S9_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M10_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S10_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M11_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S11_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M12_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S12_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M13_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S13_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M14_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S14_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M15_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_S15_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_ICACHE_BASEADDR ():
    return 0x00000000
def XPAR_MICROBLAZE_0_ICACHE_HIGHADDR ():
    return 0x3FFFFFFF
def XPAR_MICROBLAZE_0_USE_ICACHE ():
    return 0
def XPAR_MICROBLAZE_0_ALLOW_ICACHE_WR ():
    return 1
def XPAR_MICROBLAZE_0_ADDR_TAG_BITS ():
    return 0
def XPAR_MICROBLAZE_0_CACHE_BYTE_SIZE ():
    return 8192
def XPAR_MICROBLAZE_0_ICACHE_USE_FSL ():
    return 0
def XPAR_MICROBLAZE_0_ICACHE_LINE_LEN ():
    return 4
def XPAR_MICROBLAZE_0_ICACHE_ALWAYS_USED ():
    return 0
def XPAR_MICROBLAZE_0_ICACHE_INTERFACE ():
    return 0
def XPAR_MICROBLAZE_0_ICACHE_VICTIMS ():
    return 0
def XPAR_MICROBLAZE_0_ICACHE_STREAMS ():
    return 0
def XPAR_MICROBLAZE_0_ICACHE_FORCE_TAG_LUTRAM ():
    return 0
def XPAR_MICROBLAZE_0_ICACHE_DATA_WIDTH ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_IC_SUPPORTS_THREADS ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_IC_THREAD_ID_WIDTH ():
    return 1
def XPAR_MICROBLAZE_0_M_AXI_IC_SUPPORTS_READ ():
    return 1
def XPAR_MICROBLAZE_0_M_AXI_IC_SUPPORTS_WRITE ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_IC_SUPPORTS_NARROW_BURST ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_IC_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M_AXI_IC_ADDR_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M_AXI_IC_PROTOCOL ():
    return AXI4
def XPAR_MICROBLAZE_0_INTERCONNECT_M_AXI_IC_READ_ISSUING ():
    return 2
def XPAR_MICROBLAZE_0_DCACHE_BASEADDR ():
    return 0x00000000
def XPAR_MICROBLAZE_0_DCACHE_HIGHADDR ():
    return 0x3FFFFFFF
def XPAR_MICROBLAZE_0_USE_DCACHE ():
    return 0
def XPAR_MICROBLAZE_0_ALLOW_DCACHE_WR ():
    return 1
def XPAR_MICROBLAZE_0_DCACHE_ADDR_TAG ():
    return 0
def XPAR_MICROBLAZE_0_DCACHE_BYTE_SIZE ():
    return 8192
def XPAR_MICROBLAZE_0_DCACHE_USE_FSL ():
    return 0
def XPAR_MICROBLAZE_0_DCACHE_LINE_LEN ():
    return 4
def XPAR_MICROBLAZE_0_DCACHE_ALWAYS_USED ():
    return 0
def XPAR_MICROBLAZE_0_DCACHE_INTERFACE ():
    return 0
def XPAR_MICROBLAZE_0_DCACHE_USE_WRITEBACK ():
    return 0
def XPAR_MICROBLAZE_0_DCACHE_VICTIMS ():
    return 0
def XPAR_MICROBLAZE_0_DCACHE_FORCE_TAG_LUTRAM ():
    return 0
def XPAR_MICROBLAZE_0_DCACHE_DATA_WIDTH ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_DC_SUPPORTS_THREADS ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_DC_THREAD_ID_WIDTH ():
    return 1
def XPAR_MICROBLAZE_0_M_AXI_DC_SUPPORTS_READ ():
    return 1
def XPAR_MICROBLAZE_0_M_AXI_DC_SUPPORTS_WRITE ():
    return 1
def XPAR_MICROBLAZE_0_M_AXI_DC_SUPPORTS_NARROW_BURST ():
    return 0
def XPAR_MICROBLAZE_0_M_AXI_DC_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M_AXI_DC_ADDR_WIDTH ():
    return 32
def XPAR_MICROBLAZE_0_M_AXI_DC_PROTOCOL ():
    return AXI4
def XPAR_MICROBLAZE_0_M_AXI_DC_EXCLUSIVE_ACCESS ():
    return 0
def XPAR_MICROBLAZE_0_INTERCONNECT_M_AXI_DC_READ_ISSUING ():
    return 2
def XPAR_MICROBLAZE_0_INTERCONNECT_M_AXI_DC_WRITE_ISSUING ():
    return 32
def XPAR_MICROBLAZE_0_USE_MMU ():
    return 0
def XPAR_MICROBLAZE_0_MMU_DTLB_SIZE ():
    return 4
def XPAR_MICROBLAZE_0_MMU_ITLB_SIZE ():
    return 2
def XPAR_MICROBLAZE_0_MMU_TLB_ACCESS ():
    return 3
def XPAR_MICROBLAZE_0_MMU_ZONES ():
    return 16
def XPAR_MICROBLAZE_0_USE_INTERRUPT ():
    return 0
def XPAR_MICROBLAZE_0_USE_EXT_BRK ():
    return 0
def XPAR_MICROBLAZE_0_USE_EXT_NM_BRK ():
    return 0
def XPAR_MICROBLAZE_0_USE_BRANCH_TARGET_CACHE ():
    return 0
def XPAR_MICROBLAZE_0_BRANCH_TARGET_CACHE_SIZE ():
    return 0
def XPAR_MICROBLAZE_0_INTERCONNECT_M_AXI_DC_AW_REGISTER ():
    return 0
def XPAR_MICROBLAZE_0_INTERCONNECT_M_AXI_DC_W_REGISTER ():
    return 0

#******************************************************************/

def XPAR_CPU_ID ():
    return 0
def XPAR_MICROBLAZE_ID ():
    return 0
def XPAR_MICROBLAZE_SCO ():
    return 0
def XPAR_MICROBLAZE_FREQ ():
    return 100000000
def XPAR_MICROBLAZE_DATA_SIZE ():
    return 32
def XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING ():
    return 1
def XPAR_MICROBLAZE_FAULT_TOLERANT ():
    return 0 
def XPAR_MICROBLAZE_ECC_USE_CE_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_ENDIANNESS ():
    return 1
def XPAR_MICROBLAZE_AREA_OPTIMIZED ():
    return 0
def XPAR_MICROBLAZE_OPTIMIZATION ():
    return 0
def XPAR_MICROBLAZE_INTERCONNECT ():
    return 2
def XPAR_MICROBLAZE_STREAM_INTERCONNECT ():
    return 0
def XPAR_MICROBLAZE_DPLB_DWIDTH ():
    return 32
def XPAR_MICROBLAZE_DPLB_NATIVE_DWIDTH ():
    return 32
def XPAR_MICROBLAZE_DPLB_BURST_EN ():
    return 0
def XPAR_MICROBLAZE_DPLB_P2P ():
    return 0
def XPAR_MICROBLAZE_IPLB_DWIDTH ():
    return 32
def XPAR_MICROBLAZE_IPLB_NATIVE_DWIDTH ():
    return 32
def XPAR_MICROBLAZE_IPLB_BURST_EN ():
    return 0
def XPAR_MICROBLAZE_IPLB_P2P ():
    return 0
def XPAR_MICROBLAZE_M_AXI_DP_SUPPORTS_THREADS ():
    return 0
def XPAR_MICROBLAZE_M_AXI_DP_THREAD_ID_WIDTH ():
    return 1
def XPAR_MICROBLAZE_M_AXI_DP_SUPPORTS_READ ():
    return 1
def XPAR_MICROBLAZE_M_AXI_DP_SUPPORTS_WRITE ():
    return 1
def XPAR_MICROBLAZE_M_AXI_DP_SUPPORTS_NARROW_BURST ():
    return 0
def XPAR_MICROBLAZE_M_AXI_DP_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M_AXI_DP_ADDR_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M_AXI_DP_PROTOCOL ():
    return AXI4LITE
def XPAR_MICROBLAZE_M_AXI_DP_EXCLUSIVE_ACCESS ():
    return 0
def XPAR_MICROBLAZE_INTERCONNECT_M_AXI_DP_READ_ISSUING ():
    return 1
def XPAR_MICROBLAZE_INTERCONNECT_M_AXI_DP_WRITE_ISSUING ():
    return 1
def XPAR_MICROBLAZE_M_AXI_IP_SUPPORTS_THREADS ():
    return 0
def XPAR_MICROBLAZE_M_AXI_IP_THREAD_ID_WIDTH ():
    return 1
def XPAR_MICROBLAZE_M_AXI_IP_SUPPORTS_READ ():
    return 1
def XPAR_MICROBLAZE_M_AXI_IP_SUPPORTS_WRITE ():
    return 0
def XPAR_MICROBLAZE_M_AXI_IP_SUPPORTS_NARROW_BURST ():
    return 0
def XPAR_MICROBLAZE_M_AXI_IP_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M_AXI_IP_ADDR_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M_AXI_IP_PROTOCOL ():
    return AXI4LITE
def XPAR_MICROBLAZE_INTERCONNECT_M_AXI_IP_READ_ISSUING ():
    return 1
def XPAR_MICROBLAZE_D_AXI ():
    return 1
def XPAR_MICROBLAZE_D_PLB ():
    return 0
def XPAR_MICROBLAZE_D_LMB ():
    return 1
def XPAR_MICROBLAZE_I_AXI ():
    return 0
def XPAR_MICROBLAZE_I_PLB ():
    return 0
def XPAR_MICROBLAZE_I_LMB ():
    return 1
def XPAR_MICROBLAZE_USE_MSR_INSTR ():
    return 1
def XPAR_MICROBLAZE_USE_PCMP_INSTR ():
    return 1
def XPAR_MICROBLAZE_USE_BARREL ():
    return 1
def XPAR_MICROBLAZE_USE_DIV ():
    return 0
def XPAR_MICROBLAZE_USE_HW_MUL ():
    return 0
def XPAR_MICROBLAZE_USE_FPU ():
    return 0
def XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS ():
    return 0
def XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_M_AXI_I_BUS_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_M_AXI_D_BUS_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_IPLB_BUS_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_DPLB_BUS_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_FPU_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_FSL_EXCEPTION ():
    return 0
def XPAR_MICROBLAZE_PVR ():
    return 0
def XPAR_MICROBLAZE_PVR_USER1 ():
    return 0x00
def XPAR_MICROBLAZE_PVR_USER2 ():
    return 0x00000000
def XPAR_MICROBLAZE_DEBUG_ENABLED ():
    return 0
def XPAR_MICROBLAZE_NUMBER_OF_PC_BRK ():
    return 1
def XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK ():
    return 0
def XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK ():
    return 0
def XPAR_MICROBLAZE_INTERRUPT_IS_EDGE ():
    return 0
def XPAR_MICROBLAZE_EDGE_IS_POSITIVE ():
    return 1
def XPAR_MICROBLAZE_RESET_MSR ():
    return 0x00000000
def XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL ():
    return 0
def XPAR_MICROBLAZE_FSL_LINKS ():
    return 0
def XPAR_MICROBLAZE_FSL_DATA_SIZE ():
    return 32
def XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR ():
    return 0
def XPAR_MICROBLAZE_M0_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S0_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M1_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S1_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M2_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S2_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M3_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S3_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M4_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S4_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M5_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S5_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M6_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S6_AXIS_PROTOCOL (): 
    return GENERIC
def XPAR_MICROBLAZE_M7_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S7_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M8_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S8_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M9_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S9_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M10_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S10_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M11_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S11_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M12_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S12_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M13_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S13_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M14_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S14_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M15_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_S15_AXIS_PROTOCOL ():
    return GENERIC
def XPAR_MICROBLAZE_M0_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S0_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M1_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S1_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M2_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S2_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M3_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S3_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M4_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S4_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M5_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S5_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M6_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S6_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M7_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S7_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M8_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S8_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M9_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S9_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M10_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S10_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M11_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S11_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M12_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S12_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M13_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S13_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M14_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S14_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M15_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_S15_AXIS_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_ICACHE_BASEADDR ():
    return 0x00000000
def XPAR_MICROBLAZE_ICACHE_HIGHADDR ():
    return 0x3FFFFFFF
def XPAR_MICROBLAZE_USE_ICACHE ():
    return 0
def XPAR_MICROBLAZE_ALLOW_ICACHE_WR ():
    return 1
def XPAR_MICROBLAZE_ADDR_TAG_BITS ():
    return 0
def XPAR_MICROBLAZE_CACHE_BYTE_SIZE ():
    return 8192
def XPAR_MICROBLAZE_ICACHE_USE_FSL ():
    return 0
def XPAR_MICROBLAZE_ICACHE_LINE_LEN ():
    return 4
def XPAR_MICROBLAZE_ICACHE_ALWAYS_USED ():
    return 0
def XPAR_MICROBLAZE_ICACHE_INTERFACE ():
    return 0
def XPAR_MICROBLAZE_ICACHE_VICTIMS ():
    return 0
def XPAR_MICROBLAZE_ICACHE_STREAMS ():
    return 0
def XPAR_MICROBLAZE_ICACHE_FORCE_TAG_LUTRAM ():
    return 0
def XPAR_MICROBLAZE_ICACHE_DATA_WIDTH ():
    return 0
def XPAR_MICROBLAZE_M_AXI_IC_SUPPORTS_THREADS ():
    return 0
def XPAR_MICROBLAZE_M_AXI_IC_THREAD_ID_WIDTH ():
    return 1
def XPAR_MICROBLAZE_M_AXI_IC_SUPPORTS_READ ():
    return 1
def XPAR_MICROBLAZE_M_AXI_IC_SUPPORTS_WRITE ():
    return 0
def XPAR_MICROBLAZE_M_AXI_IC_SUPPORTS_NARROW_BURST ():
    return 0
def XPAR_MICROBLAZE_M_AXI_IC_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M_AXI_IC_ADDR_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M_AXI_IC_PROTOCOL ():
    return AXI4
def XPAR_MICROBLAZE_INTERCONNECT_M_AXI_IC_READ_ISSUING ():
    return 2
def XPAR_MICROBLAZE_DCACHE_BASEADDR ():
    return 0x00000000
def XPAR_MICROBLAZE_DCACHE_HIGHADDR ():
    return 0x3FFFFFFF
def XPAR_MICROBLAZE_USE_DCACHE ():
    return 0
def XPAR_MICROBLAZE_ALLOW_DCACHE_WR ():
    return 1
def XPAR_MICROBLAZE_DCACHE_ADDR_TAG ():
    return 0
def XPAR_MICROBLAZE_DCACHE_BYTE_SIZE ():
    return 8192
def XPAR_MICROBLAZE_DCACHE_USE_FSL ():
    return 0
def XPAR_MICROBLAZE_DCACHE_LINE_LEN ():
    return 4
def XPAR_MICROBLAZE_DCACHE_ALWAYS_USED ():
    return 0
def XPAR_MICROBLAZE_DCACHE_INTERFACE ():
    return 0
def XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK ():
    return 0
def XPAR_MICROBLAZE_DCACHE_VICTIMS ():
    return 0
def XPAR_MICROBLAZE_DCACHE_FORCE_TAG_LUTRAM ():
    return 0
def XPAR_MICROBLAZE_DCACHE_DATA_WIDTH ():
    return 0
def XPAR_MICROBLAZE_M_AXI_DC_SUPPORTS_THREADS ():
    return 0
def XPAR_MICROBLAZE_M_AXI_DC_THREAD_ID_WIDTH ():
    return 1
def XPAR_MICROBLAZE_M_AXI_DC_SUPPORTS_READ ():
    return 1
def XPAR_MICROBLAZE_M_AXI_DC_SUPPORTS_WRITE ():
    return 1
def XPAR_MICROBLAZE_M_AXI_DC_SUPPORTS_NARROW_BURST ():
    return 0
def XPAR_MICROBLAZE_M_AXI_DC_DATA_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M_AXI_DC_ADDR_WIDTH ():
    return 32
def XPAR_MICROBLAZE_M_AXI_DC_PROTOCOL ():
    return AXI4
def XPAR_MICROBLAZE_M_AXI_DC_EXCLUSIVE_ACCESS ():
    return 0
def XPAR_MICROBLAZE_INTERCONNECT_M_AXI_DC_READ_ISSUING ():
    return 2
def XPAR_MICROBLAZE_INTERCONNECT_M_AXI_DC_WRITE_ISSUING ():
    return 32
def XPAR_MICROBLAZE_USE_MMU ():
    return 0
def XPAR_MICROBLAZE_MMU_DTLB_SIZE ():
    return 4
def XPAR_MICROBLAZE_MMU_ITLB_SIZE ():
    return 2
def XPAR_MICROBLAZE_MMU_TLB_ACCESS ():
    return 3
def XPAR_MICROBLAZE_MMU_ZONES ():
    return 16
def XPAR_MICROBLAZE_USE_INTERRUPT ():
    return 0
def XPAR_MICROBLAZE_USE_EXT_BRK ():
    return 0
def XPAR_MICROBLAZE_USE_EXT_NM_BRK ():
    return 0
def XPAR_MICROBLAZE_USE_BRANCH_TARGET_CACHE ():
    return 0
def XPAR_MICROBLAZE_BRANCH_TARGET_CACHE_SIZE ():
    return 0
def XPAR_MICROBLAZE_INTERCONNECT_M_AXI_DC_AW_REGISTER ():
    return 0
def XPAR_MICROBLAZE_INTERCONNECT_M_AXI_DC_W_REGISTER ():
    return 0
def XPAR_MICROBLAZE_HW_VER ():
    return "8.00.b"

#******************************************************************

