`define PARA_NETFPGA_DATE 32'h0
`define PARA_NETFPGA_TIME 32'h0
`define PARA_PROJECT_ID 32'h0
`define PARA_NETFPGA_TAG 32'h0
`define PARA_BOARD_ID 32'h0
`define PARA_RESERVED_A 32'h0
`define PARA_RESERVED_B 32'h0
